on: [push]

jobs:
  pytest-linux:
    runs-on: ubuntu-latest
    name: "pytest on linux"
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "0.11.2"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Pytest
        run: uv run pytest tests
